;;; init.el --- TioT2 Emacs configuration main file -*- lexical-binding: t; -*-

;;; Some useful functions

(defun append-to-list (list values &optional append compare-fn)
  "Perform add-to-list for all values from another list"
  (dolist (val values)
    (add-to-list list val append compare-fn)))

(defun ignore-eglot-server-capabilities (&rest caps)
  "Ignore some EGLOT server capabilities"
  (append-to-list 'eglot-ignored-server-capabilities caps t))

;;; Package configuraiton

;; EMACS (Editor MACroS, configuration 'root')
(use-package emacs
  :config

  ;; Make 'custom-*' autogenerated fields to go to special file, then load them
  (custom-set-variables '(custom-file (concat user-emacs-directory "custom.el")))
  (when (file-exists-p custom-file)
    (load custom-file))

  ;; Disable top menus and scroll bars
  (menu-bar-mode -1)
  (tool-bar-mode -1)

  ;; Disable scroll bars
  (customize-set-variable 'scroll-bar-mode nil)
  (customize-set-variable 'horizontal-scroll-bar-mode nil)

  ;; Disable Emacs backup files
  (custom-set-variables '(make-backup-files nil))

  ;; Decrease font size
  (set-face-attribute 'default nil :height 93)

  ;; Make GC threshold bigger (to 128mb) to make EGLOT run faster
  (setq gc-cons-threshold (* 128 1024 1024))

  ;; Allow larger process outputs
  (setq read-process-output-max (* 1024 1024))

  ;; Set some default editing parameters
  (setq-default
   scroll-margin                3  ;; Set margin for scrolling
   scroll-conservatively      101  ;; Disable scroll 'jumping'
   indent-tabs-mode           nil  ;; Indent by spaces (instead of tabs)
   tab-width                    4  ;; Set default indent width to 4
   sentence-end-double-space  nil  ;; Disable outdate american typist convention
   c-basic-offset               4  ;; Set default value to basic offset for C language
   ))

;; Built-in package manager (just for configuration)
(use-package package
  :after emacs
  :config)

;; EVIL (Extensible VI Layer, e.g. vim-style keybindings)
(use-package evil
  :ensure t
  :config
  (evil-mode t)

  ;; Remap ':q' and ':wq' commands to not terminate Emacs instance
  (evil-ex-define-cmd "q" 'kill-current-buffer)
  (evil-ex-define-cmd "wq" (lambda ()
                             (interactive)
                             (save-buffer)
                             (kill-current-buffer)))

  ;; Make emacs to have correct tabs
  (evil-define-key 'insert global-map (kbd "TAB") 'tab-to-tab-stop)
  (evil-define-key 'insert c-mode-map (kbd "TAB") 'tab-to-tab-stop)
  (evil-define-key 'insert rust-mode-map (kbd "TAB") 'tab-to-tab-stop)
  (evil-define-key 'insert haskell-mode-map (kbd "TAB") 'tab-to-tab-stop)

  ;; Disable evil-mode in info-mode
  (evil-set-initial-state 'Info-mode 'emacs)

  ;; Set vi-style search module
  (evil-select-search-module 'evil-search-module 'evil-search))

;; EVILNC (VIM NerdCommenter package port, much
(use-package evil-nerd-commenter
  :ensure t
  :config
  (evilnc-default-hotkeys))

;; MAGIT (git gui package)
(use-package magit
  :ensure t)

;; ORG mode package
(use-package org
  :ensure t
  :config

  ;; Enable visual lines in orgmode
  (add-hook 'org-mode-hook
            (lambda ()
              (visual-line-mode))))

;; Package for CommonLisp development (SLIME improved alternative)
(use-package sly
  :ensure t
  :config
  (add-hook 'lisp-mode-hook
            (lambda ()
              (sly-mode)))
  (setq inferior-lisp-program "sbcl")
  (sly-setup))

;; Autocomplete
(use-package corfu
  :ensure t
  :config
  (global-corfu-mode)
  (custom-set-variables
   '(corfu-auto t)
   '(corfu-quit-no-match t)))

;; CORFU support for terminal. Note: This package **must** be removed after
;; switch on EMACS 31 (it will introduce required functionality out of the box)
(use-package corfu-terminal
  :ensure t
  :after corfu
  :config
  ;; Enable terminal mode then display is ont graphical
  (unless (display-graphic-p)
    (corfu-terminal-mode t)))

;; HELM (package that **significantly** improves searching-related experience)
(use-package helm
  :ensure t
  :config
  (helm-mode t)
  (global-set-key (kbd "M-x") 'helm-M-x)
  (global-set-key (kbd "C-x C-f") 'helm-find-files)
  (custom-set-variables
   '(helm-completion-style 'helm-fuzzy)
    ;; Disable strange helm navigation sh*t
   '(helm-move-to-line-cycle-in-source nil)))

;; Rust-specific package
(use-package rust-mode
  :ensure t)

;; Haskell-specific package
(use-package haskell-mode
  :ensure t)

;; EGLOT (Emacs polyGLOT, EMACS LSP client) package.
(use-package eglot
  :ensure t
  :after rust-mode haskell-mode
  :config

  ;; Bridge 'haskell-mode' and 'eglot'
  (add-to-list 'eglot-server-programs
               '(haskell-mode . ("haskell-language-server-wrapper" "--lsp")))

  ;; Configure C-like languages
  (add-hook 'c-mode-common-hook
            (lambda ()
              "C/C++/... language common hook"
              ;; (electric-pair-mode)
              (eglot-ensure)
              (display-line-numbers-mode)
              ;; Disable autoformat

              (ignore-eglot-server-capabilities
               :documentOnTypeFormattingProvider
               :inlayHintProvider)))

  ;; Configure Rust language
  (add-hook 'rust-mode-hook
            (lambda ()
              "Rust language hook"
              (display-line-numbers-mode)
              (electric-pair-mode)
              (eglot-ensure)

              ;; Disable auto-formatting and inlay hints
              (ignore-eglot-server-capabilities
               :documentOnTypeFormattingProvider
               :inlayHintProvider)))

  ;; Configure Haskell language
  (add-hook 'haskell-mode-hook
            (lambda ()
              "Haskell language hook"
              (eglot-ensure)
              (ignore-eglot-server-capabilities
               :inlayHintProvider))))

;; DAPE (Debug Adapter Protocol for Emacs, DAP support extension)
(use-package dape
  :ensure t)

;;; init.el ends here
