;;; init.el --- TioT2 Emacs configuration main file -*- lexical-binding: t; -*-

;;; Configure EMACS itself

;; Make 'custom-*' autogenerated fields to go to special file, then load them
(custom-set-variables '(custom-file (concat user-emacs-directory "custom.el")))
(when (file-exists-p custom-file)
  (load custom-file))

;; Disable top menus and scroll bars
(menu-bar-mode -1)
(tool-bar-mode -1)

;; Disable scroll bars
(customize-set-variable 'scroll-bar-mode nil)
(customize-set-variable 'horizontal-scroll-bar-mode nil)

;; Disable Emacs backup files
(custom-set-variables '(make-backup-files nil))

;; Decrease font size
(set-face-attribute 'default nil :height 93)

;; Make GC threshold bigger (to 128mb) to make EGLOT run faster
(setq gc-cons-threshold (* 128 1024 1024))

;; Allow larger process outputs
(setq read-process-output-max (* 1024 1024))

;; Set editing parameters
(setq-default
 ;; Set margin for scrolling
 scroll-margin 3

 ;; Disable scroll 'jumping'
 scroll-conservatively 101

 ;; Indent by spaces (instead of tabs)
 indent-tabs-mode nil

 ;; Set default indent width to 4
 tab-width 4

 ;; Set default value to basic offset for C language
 c-basic-offset 4)



;;; Configure packages

;; Built-in package manager itself (just for configuration)
(use-package package
  :config

  ;; Add package archives (org, melpa, melpa-stable)
  (add-to-list 'package-archives '("org"          . "https://orgmode.org/elpa/") t)
  (add-to-list 'package-archives '("melpa"        . "https://melpa.org/packages/") t)
  (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
  (package-initialize)

  ;; Prioritize stability over recency for packages
  (custom-set-variables
   '(package-archive-priorities
     '(("gnu"          . 50)
       ("nongnu"       . 40)
       ("melpa-stable" . 30)
       ("melpa"        . 20)
       ("org"          . 10)))))

;; Make evil-collection package happy
(custom-set-variables '(evil-want-keybinding nil))

;; EVIL (Extensible VI Layer, e.g. vim-style keybindings)
(use-package evil
  :ensure t
  :config
  (evil-mode t)

  ;; Remap ':q' and ':wq' commands to not terminate Emacs instance
  (evil-ex-define-cmd "q" 'kill-current-buffer)
  (evil-ex-define-cmd "wq" (lambda ()
                             (interactive)
                             (save-buffer)
                             (kill-current-buffer)))

  ;; Set vi-style search module
  (evil-select-search-module 'evil-search-module 'evil-search))

;; EVIL comment utilities
(use-package evil-commentary
  :ensure t
  :after evil
  :config
  (evil-commentary-mode))

;; EVIL-flavoured keymaps for Magit, Corfu, etc.
(use-package evil-collection
  :ensure t
  :after evil
  :config
  ;; Enable EVIL mode flavoured bindings for specific modes only
  ;; => save traditional (**documented**) key bindings for everything else
  (custom-set-variables `(evil-collection-mode-list '(corfu dired)))
  (evil-collection-init))

;; Magit (git gui package)
(use-package magit
  :ensure t)

;; ORG mode package
(use-package org
  :ensure t)

;; Package for CommonLisp development (SLIME improved alternative)
(use-package sly
  :ensure t
  :config
  (add-hook 'lisp-mode-hook (lambda () (sly-mode t)))
  (setq inferior-lisp-program "sbcl")
  (sly-setup))

;; Autocomplete
(use-package corfu
  :ensure t
  :config
  (global-corfu-mode)
  (custom-set-variables
   '(corfu-auto t)
   '(corfu-quit-no-match t)))

;; HELM (package that **significantly** improves searching-related experience)
(use-package helm
  :ensure t
  :config
  (helm-mode t)
  (global-set-key (kbd "M-x") 'helm-M-x)
  (global-set-key (kbd "C-x C-f") 'helm-find-files)
  (custom-set-variables
   '(helm-completion-style 'helm-fuzzy)
    ;; Disable strange helm navigation sh*t
   '(helm-move-to-line-cycle-in-source nil)))

;; Tree sidebar (replace?)
(use-package treemacs
  :ensure t
  :config

  ;; Make treemacs to follow project root
  (treemacs-project-follow-mode)
  (treemacs-resize-icons 14))

;; EVIL compatibility layer for 'treemacs'
(use-package treemacs-evil
  :ensure t
  :after treemacs evil)

;; Rust-specific package
(use-package rust-mode
  :ensure t)

;; Haskell-specific package
(use-package haskell-mode
  :ensure t)

(defun ignore-eglot-server-capabilities (&rest caps)
  "Ignore some EGLOT server capabilities"
  (dolist (cap caps) (add-to-list 'eglot-ignored-server-capabilities cap)))

;; EGLOT (Emacs polyGLOT, EMACS LSP client) package.
(use-package eglot
  :ensure t
  :after rust-mode haskell-mode
  :config

  ;; Bridge 'haskell-mode' and 'eglot' 
  (add-to-list 'eglot-server-programs '(haskell-mode . ("haskell-language-server-wrapper" "--lsp")))

  ;; Configure C-like languages
  (add-hook 'c-mode-common-hook
   (lambda ()
     "C/C++/... language common hook"
     ;; (electric-pair-mode)
     (eglot-ensure)
     ;; Disable autoformat

     (ignore-eglot-server-capabilities
      :documentOnTypeFormattingProvider
      :inlayHintProvider)))

  ;; Configure Rust language
  (add-hook 'rust-mode-hook
   (lambda ()
     "Rust language hook"
     (display-line-numbers-mode)
     (electric-pair-mode)
     (eglot-ensure)

     ;; Disable auto-formatting and inlay hints
     (ignore-eglot-server-capabilities
      :documentOnTypeFormattingProvider
      :inlayHintProvider)))

  ;; Configure Haskell language
  (add-hook 'haskell-mode-hook
   (lambda ()
     "Haskell language hook"
     (eglot-ensure)
     (ignore-eglot-server-capabilities
      :inlayHintProvider))))

;; Install EGLOT-Booster to increase LSP performance
(use-package eglot-booster
  :after eglot
  :vc (:url "https://github.com/jdtsmith/eglot-booster")
  :config
  (eglot-booster-mode))

;;; Some data saved for future experiments

;; (defun meow-setup-querty ()
;;   "QUERTY layout for meow mode"
;;   (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
;;   ;(meow-motion-define-key
;;   ; '("j" . meow-next)
;;   ; '("k" . meow-prev)
;;   ; '("<escape>" . ignore))

;;   (meow-leader-define-key
;;    ;; Use SPC (0-9) for digit arguments.
;;    '("1" . meow-digit-argument)
;;    '("2" . meow-digit-argument)
;;    '("3" . meow-digit-argument)
;;    '("4" . meow-digit-argument)
;;    '("5" . meow-digit-argument)
;;    '("6" . meow-digit-argument)
;;    '("7" . meow-digit-argument)
;;    '("8" . meow-digit-argument)
;;    '("9" . meow-digit-argument)
;;    '("0" . meow-digit-argument)
;;    '("/" . meow-keypad-describe-key)
;;    '("?" . meow-cheatsheet))

;;   (meow-normal-define-key
;;    '("0" . meow-expand-0)
;;    '("9" . meow-expand-9)
;;    '("8" . meow-expand-8)
;;    '("7" . meow-expand-7)
;;    '("6" . meow-expand-6)
;;    '("5" . meow-expand-5)
;;    '("4" . meow-expand-4)
;;    '("3" . meow-expand-3)
;;    '("2" . meow-expand-2)
;;    '("1" . meow-expand-1)
;;    '("-" . negative-argument)
;;    '(";" . meow-reverse)
;;    '("," . meow-inner-of-thing)
;;    '("." . meow-bounds-of-thing)
;;    '("[" . meow-beginning-of-thing)
;;    '("]" . meow-end-of-thing)
;;    '("a" . meow-append)
;;    '("A" . meow-open-below)
;;    '("b" . meow-back-word)
;;    '("B" . meow-back-symbol)
;;    '("c" . meow-change)
;;    '("d" . meow-delete)
;;    '("D" . meow-backward-delete)
;;    '("e" . meow-next-word)
;;    '("E" . meow-next-symbol)
;;    '("f" . meow-find)
;;    '("g" . meow-cancel-selection)
;;    '("G" . meow-grab)
;;    '("h" . meow-left)
;;    '("H" . meow-left-expand)
;;    '("i" . meow-insert)
;;    '("I" . meow-open-above)
;;    '("j" . meow-next)
;;    '("J" . meow-next-expand)
;;    '("k" . meow-prev)
;;    '("K" . meow-prev-expand)
;;    '("l" . meow-right)
;;    '("L" . meow-right-expand)
;;    '("m" . meow-join)
;;    '("n" . meow-search)
;;    '("o" . meow-block)
;;    '("O" . meow-to-block)
;;    '("p" . meow-yank)
;;    '("q" . meow-quit)
;;    '("Q" . meow-goto-line)
;;    '("r" . meow-replace)
;;    '("R" . meow-swap-grab)
;;    '("s" . meow-kill)
;;    '("t" . meow-till)
;;    '("u" . meow-undo)
;;    '("U" . meow-undo-in-selection)
;;    '("v" . meow-visit)
;;    '("w" . meow-mark-word)
;;    '("W" . meow-mark-symbol)
;;    '("x" . meow-line)
;;    '("X" . meow-goto-line)
;;    '("y" . meow-save)
;;    '("Y" . meow-sync-grab)
;;    '("z" . meow-pop-selection)
;;    '("'" . repeat)
;;    '("<escape>" . ignore)))

;; ;; MEOW mode (EMACS-friendly modal editing, "yet another modal editing mode for emacs")
;; (use-package meow
;;   :ensure t
;;   :config
  
;;   ;; Setup keybindings and enable global modes
;;   (meow-setup-querty)
;;   (meow-global-mode t))

;;; init.el ends here
